# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\STUFF\IDAT\Ciclo III\Ingeniería de Requerimiento de Software\EF-Maki-Yumpu\ui\login_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 500)
        MainWindow.setStyleSheet("#btn_login {\n"
"    background-color: rgb(43, 120, 228);\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"#btn_login:hover {\n"
"    background-color: rgb(30, 84, 159);\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"#btn_login:pressed {\n"
"    background-color: rgb(140, 180, 228);\n"
"}")
        self.background = QtWidgets.QWidget(MainWindow)
        self.background.setObjectName("background")
        self.container = QtWidgets.QFrame(self.background)
        self.container.setGeometry(QtCore.QRect(0, 0, 601, 501))
        self.container.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.container.setObjectName("container")
        self.label = QtWidgets.QLabel(self.container)
        self.label.setGeometry(QtCore.QRect(0, 40, 601, 91))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.container)
        self.label_2.setGeometry(QtCore.QRect(160, 180, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.txt_user = QtWidgets.QLineEdit(self.container)
        self.txt_user.setGeometry(QtCore.QRect(160, 220, 281, 31))
        font = QtGui.QFont()
        font.setFamily("century-ghotic")
        self.txt_user.setFont(font)
        self.txt_user.setText("")
        self.txt_user.setObjectName("txt_user")
        self.label_5 = QtWidgets.QLabel(self.container)
        self.label_5.setGeometry(QtCore.QRect(160, 260, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.txt_password = QtWidgets.QLineEdit(self.container)
        self.txt_password.setGeometry(QtCore.QRect(160, 300, 281, 31))
        font = QtGui.QFont()
        font.setFamily("century-ghotic")
        self.txt_password.setFont(font)
        self.txt_password.setInputMethodHints(QtCore.Qt.ImhNone)
        self.txt_password.setText("")
        self.txt_password.setObjectName("txt_password")
        self.btn_login = QtWidgets.QPushButton(self.container)
        self.btn_login.setGeometry(QtCore.QRect(160, 370, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_login.setFont(font)
        self.btn_login.setObjectName("btn_login")
        MainWindow.setCentralWidget(self.background)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:600;\">Maki Yumpu</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Usuario</span></p></body></html>"))
        self.txt_user.setPlaceholderText(_translate("MainWindow", "USER1234"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Contraseña</span></p></body></html>"))
        self.txt_password.setPlaceholderText(_translate("MainWindow", "••••••••••••"))
        self.btn_login.setText(_translate("MainWindow", "Iniciar Sesión"))
